spring.application.name=gasflow

# ===============================
# BANCO DE DADOS (POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/gasflow_db
spring.datasource.username=postgres
spring.datasource.password=Lauroand

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# THYMELEAF
# ===============================
spring.thymeleaf.cache=false

# ===============================
# TAMANHO DE ARQUIVOS NO DIRETÓRIO
# ===============================
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=100MB

# ===============================
# APLICACAO
# ===============================
gasflow.app.base-url=http://localhost:8080

# ===============================
# GMAIL API
# ===============================
gasflow.gmail.enabled=true
gasflow.gmail.application-name=GasFlow System
gasflow.gmail.sender-email=gasflowteste@gmail.com
gasflow.gmail.credentials-path=credentials.json
gasflow.gmail.tokens-directory=tokens
