package com.gasflow.gasflow.enums;

public enum StatusProcesso {

    ABERTO,
    AGUARDANDO_ANALISE_GERAF,
    REJEITADO,
    AUTORIZACAO_EMITIDA,
    AGUARDANDO_PAGAMENTO,
    PAGO,
    AGUARDANDO_RECEBIMENTO,
    RECEBIDO_CONFORME,
    RECEBIDO_NAO_CONFORME,
    NOTA_FISCAL_VALIDADA,
    ENCERRADO

}
